config/routes.rb
Rails.application.routes.draw do
  resources :keyword_mappings
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/test/eat', to:'test#eat'
  get '/test/request_headers', to: 'test#request_headers'
  get '/test/request_body', to: 'test#request_body'
  get '/test/response_headers', to: 'test#response_headers'
  get '/test/response_body', to: 'test#show_response_body'
  get '/test/sent_request', to:'test#sent_request'
  post '/webhook/testApi',to:'webhook#testApi'
  post '/webhook/sendMessage',to:'webhook#sendMessage'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/keyword_mapping.rb
class KeywordMapping < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/keyword_mappings_controller.rb
class KeywordMappingsController < ApplicationController
  before_action :set_keyword_mapping, only: [:show, :edit, :update, :destroy]

  # GET /keyword_mappings
  # GET /keyword_mappings.json
  def index
    @keyword_mappings = KeywordMapping.all
  end

  # GET /keyword_mappings/1
  # GET /keyword_mappings/1.json
  def show
  end

  # GET /keyword_mappings/new
  def new
    @keyword_mapping = KeywordMapping.new
  end

  # GET /keyword_mappings/1/edit
  def edit
  end

  # POST /keyword_mappings
  # POST /keyword_mappings.json
  def create
    @keyword_mapping = KeywordMapping.new(keyword_mapping_params)

    respond_to do |format|
      if @keyword_mapping.save
        format.html { redirect_to @keyword_mapping, notice: 'Keyword mapping was successfully created.' }
        format.json { render :show, status: :created, location: @keyword_mapping }
      else
        format.html { render :new }
        format.json { render json: @keyword_mapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keyword_mappings/1
  # PATCH/PUT /keyword_mappings/1.json
  def update
    respond_to do |format|
      if @keyword_mapping.update(keyword_mapping_params)
        format.html { redirect_to @keyword_mapping, notice: 'Keyword mapping was successfully updated.' }
        format.json { render :show, status: :ok, location: @keyword_mapping }
      else
        format.html { render :edit }
        format.json { render json: @keyword_mapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keyword_mappings/1
  # DELETE /keyword_mappings/1.json
  def destroy
    @keyword_mapping.destroy
    respond_to do |format|
      format.html { redirect_to keyword_mappings_url, notice: 'Keyword mapping was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_keyword_mapping
      @keyword_mapping = KeywordMapping.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def keyword_mapping_params
      params.require(:keyword_mapping).permit(:channel_id, :keyword, :message)
    end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
    def eat

        render plain: "猥褻吃屎"
      end 
    
      def request_headers
        render plain: request.headers.to_h.reject{ |key, value|
          key.include? '.'
        }.map{ |key, value|
          "#{key}: #{value}"
        }.sort.join("\n")
      end
    
      def response_headers
        response.headers['5566'] = 'QQ'
        render plain: response.headers.to_h.map{ |key, value|
          "#{key}: #{value}"
        }.sort.join("\n")
      end
    
      def request_body
        render plain: request.body
      end
    
      def show_response_body


        #word_cut = word[word_index+1..word.length].index("!")
        puts "===這是設定前的response.body:#{response.body}==="
        render plain: "虎哇花哈哈哈"
        puts "===這是設定後的response.body:#{response.body}==="
        word ="!猥褻"
        
        keyword_reply(word)

      end
      def count(i,j)
        i+j
      end
      def translate_to_korean(message)
        "#{message}油~"
      end
      def sent_request
        uri = URI('http://localhost:3000/test/response_body')
        http = Net::HTTP.new(uri.host, uri.port)
        http_request = Net::HTTP::Get.new(uri)
        http_response = http.request(http_request)
    
        render plain: JSON.pretty_generate({
          request_class: request.class,
          response_class: response.class,
          http_request_class: http_request.class,
          http_response_class: http_response.class
        })
      end
      def keyword_reply(received_text)
        # 學習紀錄表
        p "======這裡是 訊息 ======"
        p received_text 
        p "============"

            
            word = received_text
            word_index =word.index("!")

            if word_index.nil?
                word_check = ''
            else
                word_check = word[word_index+1..word.length].index("!")
            end

            if word_check.nil?
                p "有去除"
                p word.split('!')
                received_text = word.split('!')[1]
            else 
                p "無去除"
                received_text = ''
            end 



        
        
        # 查表
        p "======這裡是 要發送訊息 ======"
        p KeywordMapping.where(keyword:received_text).first.message
        p "============"

      end
end

app/controllers/webhook_controller.rb
require 'line/bot'
class WebhookController < ApplicationController
    protect_from_forgery with: :null_session


    def sendMessage

        reply_text = keyword_reply(received_text)

        response = pushMessage("text",reply_text)
        p "============"
        p response 
        p "============"
        head :ok



    end
    def line
        @line ||= Line::Bot::Client.new { |config|
            config.channel_secret = '6b7779dbd99c8a99e441c2e020c51d90'
            config.channel_token = 'SVc2JRCw9gMwKXOzyAEqWmGUGpE4DDVSD/5ncbqWLj6QXcZt76bHPJg1ddBDRs+33uwZv1XbMm8GmVRAMfjj/E/ERz4xh1fR78GpF2rant1hS8ijJvcHYwo2werkpVkXdMgP7w0X/6yb7BkBij9LrwdB04t89/1O/w1cDnyilFU='
        }
    end
    def pushMessage(type,text)
        return nil if text.nil?
        # 取得 reply token
        reply_token = params['events'][0]['replyToken']
        
        p "======這裡是 reply_token ======"
        p reply_token 
        p "============"
        p "======這裡是 傳送文字 ======"
        p text 
        p "============"
        message = 
        {
            type: type,
            text: text
        }
        line.reply_message(reply_token, message)
    end


    def received_text
    message = params['events'][0]['message']
    message['text'] unless message.nil?
    end

    def keyword_reply(received_text)
    # 學習紀錄表
    p "======這裡是 訊息 ======"
    p received_text 
    p "============"

    if  received_text.nil?        
         nil
    else
        word = received_text
        word_index =word.index("!")

        if word_index.nil?
            word_check = ''
        else
            word_check = word[word_index+1..word.length].index("!")
        end

        if word_check.nil?
            p "有去除"
            p word.split('!')
            received_text = word.split('!')[1]
             # 查表
            p "======這裡是 要發送訊息 ======"
            p KeywordMapping.where(keyword:received_text).first.message
            p "============"
            KeywordMapping.where(keyword:received_text).first.message
        else 
            p "無去除"
            nil
        end 

    end


    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/keyword_mappings_helper.rb
module KeywordMappingsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/webhook_helper.rb
module WebhookHelper
end

app/views/keyword_mappings/_form.html.erb
<%= form_with(model: keyword_mapping) do |form| %>
  <% if keyword_mapping.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(keyword_mapping.errors.count, "error") %> prohibited this keyword_mapping from being saved:</h2>

      <ul>
        <% keyword_mapping.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :keyword %>
    <%= form.text_field :keyword %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_field :message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/keyword_mappings/edit.html.erb
<h1>Editing Keyword Mapping</h1>

<%= render 'form', keyword_mapping: @keyword_mapping %>

<%= link_to 'Show', @keyword_mapping %> |
<%= link_to 'Back', keyword_mappings_path %>

app/views/keyword_mappings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Keyword Mappings</h1>

<table>
  <thead>
    <tr>
      <th>Keyword</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @keyword_mappings.each do |keyword_mapping| %>
      <tr>
        <td><%= keyword_mapping.keyword %></td>
        <td><%= keyword_mapping.message %></td>
        <td><%= link_to 'Show', keyword_mapping %></td>
        <td><%= link_to 'Edit', edit_keyword_mapping_path(keyword_mapping) %></td>
        <td><%= link_to 'Destroy', keyword_mapping, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Keyword Mapping', new_keyword_mapping_path %>

app/views/keyword_mappings/new.html.erb
<h1>New Keyword Mapping</h1>

<%= render 'form', keyword_mapping: @keyword_mapping %>

<%= link_to 'Back', keyword_mappings_path %>

app/views/keyword_mappings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Keyword:</strong>
  <%= @keyword_mapping.keyword %>
</p>

<p>
  <strong>Message:</strong>
  <%= @keyword_mapping.message %>
</p>

<%= link_to 'Edit', edit_keyword_mapping_path(@keyword_mapping) %> |
<%= link_to 'Back', keyword_mappings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LineBot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>